# Jekyll Settings

title: Toko Putri
description: Selamat datang di Toko Putri, destinasi fashion online Anda!

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter:
  stackoverflow: 
  youtube: 
  
disqus:
google_analytics:

url: https://tokoputri.pages.dev
baseurl: ""

markdown: kramdown
highlighter: pygments
permalink: /:title/

version: v2.0.1

sass:
  sass_dir: assets/scss
  style: :compressed 

plugins:
  - jekyll-dotenv
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Xendit Defaults
xendit_options:
  - test
  - live

XENDIT_LIVE_URL: "<%= ENV['live_url'] %>"
XENDIT_TEST_URL: "<%= ENV['test_url'] %>"

# Firebase
api_key: "<%= ENV['api_key'] %>"
auth_domain: "<%= ENV['auth_domain'] %>"
project_id: "<%= ENV['project_id'] %>"
storage_bucket: "<%= ENV['storage_bucket'] %>"
sender_id: "<%= ENV['sender_id'] %>"
app_id: "<%= ENV['app_id'] %>"
measure_id: "<%= ENV['measure_id'] %>"

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'
    
# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
    
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
