# Jekyll Settings
port: 1111

title: Toko Putri
description: Belanja fashion kekinian, nyaman, dan berkualitas. Buktikan gayamu sekarang!

avatar: https://ionicframework.com/docs/img/demos/avatar.svg
logo: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter:
  stackoverflow: 
  youtube: 
  
disqus:
google_analytics:

url: https://tokoputri.pages.dev
baseurl: ""

markdown: kramdown
highlighter: pygments
permalink: /:title/

version: v2.0.1

sass:
  sass_dir: assets/scss
  style: :compressed


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - dotenv

plugins_dir: _plugins

# Xendit Defaults
xendit_options:
  - test
  - live

XENDIT_LIVE_URL: "<%= ENV['live_url'] %>"
XENDIT_TEST_URL: "<%= ENV['test_url'] %>"

# Firebase
api_key: "<%= ENV['api_key'] %>"
auth_domain: "<%= ENV['auth_domain'] %>"
project_id: "<%= ENV['project_id'] %>"
storage_bucket: "<%= ENV['storage_bucket'] %>"
sender_id: "<%= ENV['sender_id'] %>"
app_id: "<%= ENV['app_id'] %>"
measure_id: "<%= ENV['measure_id'] %>"
bot_token: "<%= ENV['bot_token'] %>"
chat_id: "<%= ENV['chat_id'] %>"
test-mode: "<%= ENV['test_mode'] %>"

jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'
    
# HTML Compression
# - http://jch.penibelst.de/
    
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md