source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-archives'
gem 'jekyll-paginate'
gem 'dotenv', '~> 3.1', '>= 3.1.7'
gem 'bootstrap', '~> 5.2', '>= 5.2.3'
gem 'wdm'
